
package core.soap_web_services;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Application", targetNamespace = "soap_web_services.core")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Application {


    /**
     * 
     * @param times
     * @param name
     * @return
     *     returns core.soap_web_services.StringArray
     */
    @WebMethod(operationName = "say_hello", action = "say_hello")
    @WebResult(name = "say_helloResult", targetNamespace = "soap_web_services.core")
    @RequestWrapper(localName = "say_hello", targetNamespace = "soap_web_services.core", className = "core.soap_web_services.SayHello")
    @ResponseWrapper(localName = "say_helloResponse", targetNamespace = "soap_web_services.core", className = "core.soap_web_services.SayHelloResponse")
    public StringArray sayHello(
        @WebParam(name = "name", targetNamespace = "soap_web_services.core")
        String name,
        @WebParam(name = "times", targetNamespace = "soap_web_services.core")
        BigInteger times);

}
