
package core.soap_web_services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MedicationPlanService", targetNamespace = "soap_web_services.core", wsdlLocation = "http://172.28.1.5:8000/doctor_wsdl/")
public class MedicationPlanService
    extends Service
{

    private final static URL MEDICATIONPLANSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEDICATIONPLANSERVICE_EXCEPTION;
    private final static QName MEDICATIONPLANSERVICE_QNAME = new QName("soap_web_services.core", "MedicationPlanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.28.1.5:8000/doctor_wsdl/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MEDICATIONPLANSERVICE_WSDL_LOCATION = url;
        MEDICATIONPLANSERVICE_EXCEPTION = e;
    }

    public MedicationPlanService() {
        super(__getWsdlLocation(), MEDICATIONPLANSERVICE_QNAME);
    }

    public MedicationPlanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEDICATIONPLANSERVICE_QNAME, features);
    }

    public MedicationPlanService(URL wsdlLocation) {
        super(wsdlLocation, MEDICATIONPLANSERVICE_QNAME);
    }

    public MedicationPlanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEDICATIONPLANSERVICE_QNAME, features);
    }

    public MedicationPlanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MedicationPlanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication() {
        return super.getPort(new QName("soap_web_services.core", "Application"), Application.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication(WebServiceFeature... features) {
        return super.getPort(new QName("soap_web_services.core", "Application"), Application.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEDICATIONPLANSERVICE_EXCEPTION!= null) {
            throw MEDICATIONPLANSERVICE_EXCEPTION;
        }
        return MEDICATIONPLANSERVICE_WSDL_LOCATION;
    }

}
