# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.3'

# Define services
services:
  hk-nginx:
    container_name: hk-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 8087:8087
      - 8088:8088
      - 8000:8000
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - java_soap_web_service
      - backend
      - python_soap_web_service

  # Database Service (Mysql)
  hk-mysql:
     container_name: hk-mysql
     image: mysql/mysql-server:5.7
     healthcheck:
       test: "/usr/bin/mysql --user=root --password=rootpasswd --execute \"SHOW DATABASES;\""
       interval: 2s
       timeout: 20s
       retries: 10
     environment:
      MYSQL_DATABASE: ds_assignment1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
     ports:
     - "3306:3306"
     restart: always

  java_soap_web_service:
    restart: always
    build: ./java_soap_web_service
    working_dir: /java_soap_web_service
    volumes:
      - ./java_soap_web_service:/java_soap_web_service
      - ~/.m2:/root/.m2
    expose:
      - "8087"
    command: mvn clean spring-boot:run
    depends_on:
      - hk-mysql

  backend:
    restart: always
    build: ./backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
      - ~/.m2:/root/.m2
    expose:
      - "8088"
    command: mvn clean spring-boot:run
    depends_on:
      - hk-mysql
      - java_soap_web_service

  python_soap_web_service:
    restart: always
    build: ./soap_web_services
    working_dir: /code
    volumes:
      - ./soap_web_services:/code
    expose:
      - "8000"
    command: /bin/bash -c "sleep 7; python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - hk-mysql
      - java_soap_web_service

  producer:
    restart: always
    build: ./producer
    working_dir: /code
    volumes:
      - ./producer:/code
    command: /bin/bash -c "sleep 10; python -m pilotproducer False"
    depends_on:
      - java_soap_web_service
      - hk-mysql
      - rabbitmq
    environment:
      - RABBITMQ_PASS=guest
      - RABBITMQ_USER=guest
    links:
      - rabbitmq:rabbitmq

  rabbitmq:
    image: 'rabbitmq:3'
    container_name: rabbitmq
    expose:
      - "5672"
      - "15672"