
package core.recommendation_web_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ActivitiesPortService", targetNamespace = "core/recommendation-web-service", wsdlLocation = "http://localhost:8087/app/ws/activities.wsdl")
public class ActivitiesPortService
    extends Service
{

    private final static URL ACTIVITIESPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTIVITIESPORTSERVICE_EXCEPTION;
    private final static QName ACTIVITIESPORTSERVICE_QNAME = new QName("core/recommendation-web-service", "ActivitiesPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8087/app/ws/activities.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIVITIESPORTSERVICE_WSDL_LOCATION = url;
        ACTIVITIESPORTSERVICE_EXCEPTION = e;
    }

    public ActivitiesPortService() {
        super(__getWsdlLocation(), ACTIVITIESPORTSERVICE_QNAME);
    }

    public ActivitiesPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIVITIESPORTSERVICE_QNAME, features);
    }

    public ActivitiesPortService(URL wsdlLocation) {
        super(wsdlLocation, ACTIVITIESPORTSERVICE_QNAME);
    }

    public ActivitiesPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIVITIESPORTSERVICE_QNAME, features);
    }

    public ActivitiesPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActivitiesPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ActivitiesPort
     */
    @WebEndpoint(name = "ActivitiesPortSoap11")
    public ActivitiesPort getActivitiesPortSoap11() {
        return super.getPort(new QName("core/recommendation-web-service", "ActivitiesPortSoap11"), ActivitiesPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActivitiesPort
     */
    @WebEndpoint(name = "ActivitiesPortSoap11")
    public ActivitiesPort getActivitiesPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("core/recommendation-web-service", "ActivitiesPortSoap11"), ActivitiesPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIVITIESPORTSERVICE_EXCEPTION!= null) {
            throw ACTIVITIESPORTSERVICE_EXCEPTION;
        }
        return ACTIVITIESPORTSERVICE_WSDL_LOCATION;
    }

}
