
package core.recommendation_web_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ActivitiesPort", targetNamespace = "core/recommendation-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ActivitiesPort {


    /**
     * 
     * @param activityRecommendationRequest
     * @return
     *     returns core.recommendation_web_service.ActivityRecommendationResponse
     */
    @WebMethod(operationName = "ActivityRecommendation")
    @WebResult(name = "ActivityRecommendationResponse", targetNamespace = "core/recommendation-web-service", partName = "ActivityRecommendationResponse")
    public ActivityRecommendationResponse activityRecommendation(
        @WebParam(name = "ActivityRecommendationRequest", targetNamespace = "core/recommendation-web-service", partName = "ActivityRecommendationRequest")
        ActivityRecommendationRequest activityRecommendationRequest);

}
