# Generated by Django 2.2.7 on 2019-11-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('activity_lavel', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('is_violated', models.BooleanField(blank=True, db_column='isViolated', null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dosage', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'drug',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HibernateSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_val', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hibernate_sequence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationPlan',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('intake_interval_period', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medication_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationPlanTaken',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day', models.DateField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('intake_interval_end', models.IntegerField(blank=True, null=True)),
                ('intake_interval_start', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medication_plan_taken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'side_effect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.User')),
            ],
            options={
                'db_table': 'caregiver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.User')),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrugToSideEffects',
            fields=[
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Drug')),
            ],
            options={
                'db_table': 'drug_to_side_effects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicationPlanToDrugs',
            fields=[
                ('medication_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.MedicationPlan')),
            ],
            options={
                'db_table': 'medication_plan_to_drugs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.User')),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
