# Generated by Django 2.2.7 on 2019-11-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationPlanInterval',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('day', models.DateField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('intake_interval_end', models.IntegerField(blank=True, null=True)),
                ('intake_interval_start', models.IntegerField(blank=True, null=True)),
                ('taken_on_time', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medication_plan_interval',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MedicationPlanTaken',
        ),
    ]
