# Generated by Django 2.2.7 on 2019-11-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191130_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'activity_recommendation',
                'managed': False,
            },
        ),
    ]
